#!/usr/bin/env python3
"""SPA 用データ JS（用語・実践・過去問・一問一答）を1ファイルにまとめる。"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTS = (
    "eisei1-data-glossary.js",
    "eisei1-master-data.js",
    "eisei1-data-ichimon.js",
)
OUT = ROOT / "eisei1-data-bundle.js"


def main() -> int:
    chunks: list[str] = []
    for name in PARTS:
        path = ROOT / name
        if not path.is_file():
            print(f"bundle_spa_data_js.py: 必須ファイルがありません: {path}", file=sys.stderr)
            return 1
        text = path.read_text(encoding="utf-8").strip()
        if text:
            chunks.append(text)
    header = "/* AUTO-GENERATED by tools/bundle_spa_data_js.py — 編集しない */\n"
    OUT.write_text(header + "\n\n".join(chunks) + "\n", encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"bundle_spa_data_js.py: {OUT.name} ({kb:.0f} KiB) を生成しました。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
